/*
 * Copyright (C) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Description: Definition of cap_module errno exported to userspace
 * Author: Huawei OS Kernel Lab
 * Create: Thu Jul 25 12:47:00 2019
 */
/*
 * Must choose one GRANT type from ALL/NO/COARSE/FINE
 * Must choose one GRANTMOVE type from ALL/NO/COARSE
 */
CAPTYPE(Module, 14, CAPFINEGRANT(Module)
		    CAPNOGRANTMOVE(Module)
		    CAPNODEFAULTCREF(Module)
		    CAPRAWCREFRLOOKUP(Module)
		    CAPDEFAULTSIZE(Module),
	CAPMETHOD(Module, Ioctl)
	CAPMETHOD(Module, Info)
	CAPMETHOD(Module, BindModif)
	CAPMETHOD(Module, UnbindModif)

	CAPERRNO(Module, EHMERROR, MODULE_INNER_ERR, "E_HM_MODULE_INNER_ERR")
	CAPERRNO(Module, EHMERROR, MODULE_PARA_ERR, "E_HM_MODULE_PARA_ERR")
	CAPERRNO(Module, EHMERROR, MODULE_OUT_OF_MEM, "E_HM_MODULE_OUT_OF_MEM")
	CAPERRNO(Module, EHMERROR, MODULE_UNINIT, "E_HM_MODULE_UNINIT")
	CAPERRNO(Module, EHMERROR, MODULE_NO_PROCESS, "E_HM_MODULE_NO_PROCESS")
	CAPERRNO(Module, EHMERROR, MODULE_PROCESS_EXIT, "E_HM_MODULE_PROCESS_EXIT")
	CAPERRNO(Module, EHMERROR, MODULE_NO_SUBSCRIBE_THREAD, "E_HM_MODULE_NO_SUBSCRIBE_THREAD")
	CAPERRNO(Module, EHMERROR, MODULE_NON_SCHED_GRP_MUL_THREAD, "E_HM_MODULE_NON_SCHED_GRP_MUL_THREAD")
	CAPERRNO(Module, EHMERROR, MODULE_GRP_INVALID, "E_HM_MODULE_GRP_INVALID")
	CAPERRNO(Module, EHMERROR, MODULE_PUBLISH_QUE_FULL, "E_HM_MODULE_PUBLISH_QUE_FULL")
	CAPERRNO(Module, EHMERROR, MODULE_NO_GRP, "E_HM_MODULE_NO_GRP")
	CAPERRNO(Module, EHMERROR, MODULE_GRP_EXIT, "E_HM_MODULE_GRP_EXIT")
	CAPERRNO(Module, EHMERROR, MODULE_THREAD_EXCEEDS_SPEC, "E_HM_MODULE_THREAD_EXCEEDS_SPEC")
	CAPERRNO(Module, EHMERROR, MODULE_RUN_IN_ILLEGAL_CPU, "E_HM_MODULE_RUN_IN_ILLEGAL_CPU")
	CAPERRNO(Module, EHMERROR, MODULE_WAIT_TIMEOUT, "E_HM_MODULE_WAIT_TIMEOUT")
	CAPERRNO(Module, EHMERROR, MODULE_WAIT_FAILED, "E_HM_MODULE_WAIT_FAILED")
	CAPERRNO(Module, EHMERROR, MODULE_WAIT_INTERRUPT, "E_HM_MODULE_WAIT_INTERRUPT")
	CAPERRNO(Module, EHMERROR, MODULE_THREAD_NOT_RUNNIG, "E_HM_MODULE_THREAD_NOT_RUNNIG")
	CAPERRNO(Module, EHMERROR, MODULE_PROCESS_NOT_MATCH, "E_HM_MODULE_PROCESS_NOT_MATCH")
	CAPERRNO(Module, EHMERROR, MODULE_EVENT_NOT_MATCH, "E_HM_MODULE_EVENT_NOT_MATCH")
	CAPERRNO(Module, EHMERROR, MODULE_PROCESS_REPEAT_ADD, "E_HM_MODULE_PROCESS_REPEAT_ADD")
	CAPERRNO(Module, EHMERROR, MODULE_GRP_NON_SCHED, "E_HM_MODULE_GRP_NON_SCHED")
	CAPERRNO(Module, EHMERROR, MODULE_NO_EVENT, "E_HM_MODULE_NO_EVENT")
	CAPERRNO(Module, EHMERROR, MODULE_COPY_USER, "E_HM_MODULE_COPY_USER")
	)

#ifdef CAP_EXPORT_API
#ifndef CAP_MODULE_API_EXPORTED
#define CAP_MODULE_API_EXPORTED

enum {
	CRIGHT_MODULE_MAX
};

#endif
#endif
