/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Description: APIs compatible with userspace-auditd.
 * Author: Huawei OS Kernel Lab
 * Create: Thu Dec 17 10:06:34 2020
 */

#ifndef ULIBS_LIBAUDIT_AUDIT_H
#define ULIBS_LIBAUDIT_AUDIT_H

#include "hm_audit.h"

// make macros compatible with linux/audit.h
#define AUDIT_GET                                    HM_AUDIT_GET
#define AUDIT_SET                                    HM_AUDIT_SET
#define AUDIT_LIST                                   HM_AUDIT_LIST
#define AUDIT_ADD                                    HM_AUDIT_ADD
#define AUDIT_DEL                                    HM_AUDIT_DEL
#define AUDIT_USER                                   HM_AUDIT_USER
#define AUDIT_LOGIN                                  HM_AUDIT_LOGIN
#define AUDIT_WATCH_INS                              HM_AUDIT_WATCH_INS
#define AUDIT_WATCH_REM                              HM_AUDIT_WATCH_REM
#define AUDIT_WATCH_LIST                             HM_AUDIT_WATCH_LIST
#define AUDIT_SIGNAL_INFO                            HM_AUDIT_SIGNAL_INFO
#define AUDIT_ADD_RULE                               HM_AUDIT_ADD_RULE
#define AUDIT_DEL_RULE                               HM_AUDIT_DEL_RULE
#define AUDIT_LIST_RULES                             HM_AUDIT_LIST_RULES
#define AUDIT_TRIM                                   HM_AUDIT_TRIM
#define AUDIT_MAKE_EQUIV                             HM_AUDIT_MAKE_EQUIV
#define AUDIT_TTY_GET                                HM_AUDIT_TTY_GET
#define AUDIT_TTY_SET                                HM_AUDIT_TTY_SET
#define AUDIT_SET_FEATURE                            HM_AUDIT_SET_FEATURE
#define AUDIT_GET_FEATURE                            HM_AUDIT_GET_FEATURE
#define AUDIT_FIRST_USER_MSG                         HM_AUDIT_FIRST_USER_MSG
#define AUDIT_USER_AVC                               HM_AUDIT_USER_AVC
#define AUDIT_USER_TTY                               HM_AUDIT_USER_TTY
#define AUDIT_LAST_USER_MSG                          HM_AUDIT_LAST_USER_MSG
#define AUDIT_FIRST_USER_MSG2                        HM_AUDIT_FIRST_USER_MSG2
#define AUDIT_LAST_USER_MSG2                         HM_AUDIT_LAST_USER_MSG2
#define AUDIT_DAEMON_START                           HM_AUDIT_DAEMON_START
#define AUDIT_DAEMON_END                             HM_AUDIT_DAEMON_END
#define AUDIT_DAEMON_ABORT                           HM_AUDIT_DAEMON_ABORT
#define AUDIT_DAEMON_CONFIG                          HM_AUDIT_DAEMON_CONFIG
#define AUDIT_SYSCALL                                HM_AUDIT_SYSCALL
#define AUDIT_PATH                                   HM_AUDIT_PATH
#define AUDIT_IPC                                    HM_AUDIT_IPC
#define AUDIT_SOCKETCALL                             HM_AUDIT_SOCKETCALL
#define AUDIT_CONFIG_CHANGE                          HM_AUDIT_CONFIG_CHANGE
#define AUDIT_SOCKADDR                               HM_AUDIT_SOCKADDR
#define AUDIT_CWD                                    HM_AUDIT_CWD
#define AUDIT_EXECVE                                 HM_AUDIT_EXECVE
#define AUDIT_IPC_SET_PERM                           HM_AUDIT_IPC_SET_PERM
#define AUDIT_MQ_OPEN                                HM_AUDIT_MQ_OPEN
#define AUDIT_MQ_SENDRECV                            HM_AUDIT_MQ_SENDRECV
#define AUDIT_MQ_NOTIFY                              HM_AUDIT_MQ_NOTIFY
#define AUDIT_MQ_GETSETATTR                          HM_AUDIT_MQ_GETSETATTR
#define AUDIT_KERNEL_OTHER                           HM_AUDIT_KERNEL_OTHER
#define AUDIT_FD_PAIR                                HM_AUDIT_FD_PAIR
#define AUDIT_OBJ_PID                                HM_AUDIT_OBJ_PID
#define AUDIT_TTY                                    HM_AUDIT_TTY
#define AUDIT_EOE                                    HM_AUDIT_EOE
#define AUDIT_BPRM_FCAPS                             HM_AUDIT_BPRM_FCAPS
#define AUDIT_CAPSET                                 HM_AUDIT_CAPSET
#define AUDIT_MMAP                                   HM_AUDIT_MMAP
#define AUDIT_NETFILTER_PKT                          HM_AUDIT_NETFILTER_PKT
#define AUDIT_NETFILTER_CFG                          HM_AUDIT_NETFILTER_CFG
#define AUDIT_SECCOMP                                HM_AUDIT_SECCOMP
#define AUDIT_PROCTITLE                              HM_AUDIT_PROCTITLE
#define AUDIT_FEATURE_CHANGE                         HM_AUDIT_FEATURE_CHANGE
#define AUDIT_REPLACE                                HM_AUDIT_REPLACE
#define AUDIT_KERN_MODULE                            HM_AUDIT_KERN_MODULE
#define AUDIT_FANOTIFY                               HM_AUDIT_FANOTIFY
#define AUDIT_TIME_INJOFFSET                         HM_AUDIT_TIME_INJOFFSET
#define AUDIT_TIME_ADJNTPVAL                         HM_AUDIT_TIME_ADJNTPVAL
#define AUDIT_BPF                                    HM_AUDIT_BPF
#define AUDIT_EVENT_LISTENER                         HM_AUDIT_EVENT_LISTENER
#define AUDIT_AVC                                    HM_AUDIT_AVC
#define AUDIT_SELINUX_ERR                            HM_AUDIT_SELINUX_ERR
#define AUDIT_AVC_PATH                               HM_AUDIT_AVC_PATH
#define AUDIT_MAC_POLICY_LOAD                        HM_AUDIT_MAC_POLICY_LOAD
#define AUDIT_MAC_STATUS                             HM_AUDIT_MAC_STATUS
#define AUDIT_MAC_CONFIG_CHANGE                      HM_AUDIT_MAC_CONFIG_CHANGE
#define AUDIT_MAC_UNLBL_ALLOW                        HM_AUDIT_MAC_UNLBL_ALLOW
#define AUDIT_MAC_CIPSOV4_ADD                        HM_AUDIT_MAC_CIPSOV4_ADD
#define AUDIT_MAC_CIPSOV4_DEL                        HM_AUDIT_MAC_CIPSOV4_DEL
#define AUDIT_MAC_MAP_ADD                            HM_AUDIT_MAC_MAP_ADD
#define AUDIT_MAC_MAP_DEL                            HM_AUDIT_MAC_MAP_DEL
#define AUDIT_MAC_IPSEC_ADDSA                        HM_AUDIT_MAC_IPSEC_ADDSA
#define AUDIT_MAC_IPSEC_DELSA                        HM_AUDIT_MAC_IPSEC_DELSA
#define AUDIT_MAC_IPSEC_ADDSPD                       HM_AUDIT_MAC_IPSEC_ADDSPD
#define AUDIT_MAC_IPSEC_DELSPD                       HM_AUDIT_MAC_IPSEC_DELSPD
#define AUDIT_MAC_IPSEC_EVENT                        HM_AUDIT_MAC_IPSEC_EVENT
#define AUDIT_MAC_UNLBL_STCADD                       HM_AUDIT_MAC_UNLBL_STCADD
#define AUDIT_MAC_UNLBL_STCDEL                       HM_AUDIT_MAC_UNLBL_STCDEL
#define AUDIT_MAC_CALIPSO_ADD                        HM_AUDIT_MAC_CALIPSO_ADD
#define AUDIT_MAC_CALIPSO_DEL                        HM_AUDIT_MAC_CALIPSO_DEL
#define AUDIT_FIRST_KERN_ANOM_MSG                    HM_AUDIT_FIRST_KERN_ANOM_MSG
#define AUDIT_LAST_KERN_ANOM_MSG                     HM_AUDIT_LAST_KERN_ANOM_MSG
#define AUDIT_ANOM_PROMISCUOUS                       HM_AUDIT_ANOM_PROMISCUOUS
#define AUDIT_ANOM_ABEND                             HM_AUDIT_ANOM_ABEND
#define AUDIT_ANOM_LINK                              HM_AUDIT_ANOM_LINK
#define AUDIT_ANOM_CREAT                             HM_AUDIT_ANOM_CREAT
#define AUDIT_INTEGRITY_DATA                         HM_AUDIT_INTEGRITY_DATA
#define AUDIT_INTEGRITY_METADATA                     HM_AUDIT_INTEGRITY_METADATA
#define AUDIT_INTEGRITY_STATUS                       HM_AUDIT_INTEGRITY_STATUS
#define AUDIT_INTEGRITY_HASH                         HM_AUDIT_INTEGRITY_HASH
#define AUDIT_INTEGRITY_PCR                          HM_AUDIT_INTEGRITY_PCR
#define AUDIT_INTEGRITY_RULE                         HM_AUDIT_INTEGRITY_RULE
#define AUDIT_INTEGRITY_EVM_XATTR                    HM_AUDIT_INTEGRITY_EVM_XATTR
#define AUDIT_INTEGRITY_POLICY_RULE                  HM_AUDIT_INTEGRITY_POLICY_RULE
#define AUDIT_KERNEL                                 HM_AUDIT_KERNEL
#define AUDIT_FILTER_USER                            HM_AUDIT_FILTER_USER
#define AUDIT_FILTER_TASK                            HM_AUDIT_FILTER_TASK
#define AUDIT_FILTER_ENTRY                           HM_AUDIT_FILTER_ENTRY
#define AUDIT_FILTER_WATCH                           HM_AUDIT_FILTER_WATCH
#define AUDIT_FILTER_EXIT                            HM_AUDIT_FILTER_EXIT
#define AUDIT_FILTER_EXCLUDE                         HM_AUDIT_FILTER_EXCLUDE
#define AUDIT_FILTER_TYPE                            HM_AUDIT_FILTER_TYPE
#define AUDIT_FILTER_FS                              HM_AUDIT_FILTER_FS
#define AUDIT_NR_FILTERS                             HM_AUDIT_NR_FILTERS
#define AUDIT_FILTER_PREPEND                         HM_AUDIT_FILTER_PREPEND
#define AUDIT_NEVER                                  HM_AUDIT_NEVER
#define AUDIT_POSSIBLE                               HM_AUDIT_POSSIBLE
#define AUDIT_ALWAYS                                 HM_AUDIT_ALWAYS
#define AUDIT_PID                                    HM_AUDIT_PID
#define AUDIT_UID                                    HM_AUDIT_UID
#define AUDIT_EUID                                   HM_AUDIT_EUID
#define AUDIT_SUID                                   HM_AUDIT_SUID
#define AUDIT_FSUID                                  HM_AUDIT_FSUID
#define AUDIT_GID                                    HM_AUDIT_GID
#define AUDIT_EGID                                   HM_AUDIT_EGID
#define AUDIT_SGID                                   HM_AUDIT_SGID
#define AUDIT_FSGID                                  HM_AUDIT_FSGID
#define AUDIT_LOGINUID                               HM_AUDIT_LOGINUID
#define AUDIT_PERS                                   HM_AUDIT_PERS
#define AUDIT_ARCH                                   HM_AUDIT_ARCH
#define AUDIT_MSGTYPE                                HM_AUDIT_MSGTYPE
#define AUDIT_SUBJ_USER                              HM_AUDIT_SUBJ_USER
#define AUDIT_SUBJ_ROLE                              HM_AUDIT_SUBJ_ROLE
#define AUDIT_SUBJ_TYPE                              HM_AUDIT_SUBJ_TYPE
#define AUDIT_SUBJ_SEN                               HM_AUDIT_SUBJ_SEN
#define AUDIT_SUBJ_CLR                               HM_AUDIT_SUBJ_CLR
#define AUDIT_PPID                                   HM_AUDIT_PPID
#define AUDIT_OBJ_USER                               HM_AUDIT_OBJ_USER
#define AUDIT_OBJ_ROLE                               HM_AUDIT_OBJ_ROLE
#define AUDIT_OBJ_TYPE                               HM_AUDIT_OBJ_TYPE
#define AUDIT_OBJ_LEV_LOW                            HM_AUDIT_OBJ_LEV_LOW
#define AUDIT_OBJ_LEV_HIGH                           HM_AUDIT_OBJ_LEV_HIGH
#define AUDIT_LOGINUID_SET                           HM_AUDIT_LOGINUID_SET
#define AUDIT_SESSIONID                              HM_AUDIT_SESSIONID
#define AUDIT_FSTYPE                                 HM_AUDIT_FSTYPE
#define AUDIT_DEVMAJOR                               HM_AUDIT_DEVMAJOR
#define AUDIT_DEVMINOR                               HM_AUDIT_DEVMINOR
#define AUDIT_INODE                                  HM_AUDIT_INODE
#define AUDIT_EXIT                                   HM_AUDIT_EXIT
#define AUDIT_SUCCESS                                HM_AUDIT_SUCCESS
#define AUDIT_WATCH                                  HM_AUDIT_WATCH
#define AUDIT_PERM                                   HM_AUDIT_PERM
#define AUDIT_DIR                                    HM_AUDIT_DIR
#define AUDIT_FILETYPE                               HM_AUDIT_FILETYPE
#define AUDIT_OBJ_UID                                HM_AUDIT_OBJ_UID
#define AUDIT_OBJ_GID                                HM_AUDIT_OBJ_GID
#define AUDIT_FIELD_COMPARE                          HM_AUDIT_FIELD_COMPARE
#define AUDIT_EXE                                    HM_AUDIT_EXE
#define AUDIT_SADDR_FAM                              HM_AUDIT_SADDR_FAM
#define AUDIT_ARG0                                   HM_AUDIT_ARG0
#define AUDIT_ARG1                                   HM_AUDIT_ARG1
#define AUDIT_ARG2                                   HM_AUDIT_ARG2
#define AUDIT_ARG3                                   HM_AUDIT_ARG3
#define AUDIT_FILTERKEY                              HM_AUDIT_FILTERKEY
#define AUDIT_NEGATE                                 HM_AUDIT_NEGATE
#define AUDIT_MAX_FIELDS                             HM_AUDIT_MAX_FIELDS
#define AUDIT_MAX_KEY_LEN                            HM_AUDIT_MAX_KEY_LEN
#define AUDIT_BITMASK_SIZE                           HM_AUDIT_BITMASK_SIZE
#define AUDIT_BITS_IN_WORD                           HM_AUDIT_BITS_IN_WORD
#define AUDIT_WORD(nr)                               HM_AUDIT_WORD(nr)
#define AUDIT_BIT(nr)                                HM_AUDIT_BIT(nr)
#define AUDIT_SYSCALL_CLASSES                        HM_AUDIT_SYSCALL_CLASSES
#define AUDIT_CLASS_DIR_WRITE                        HM_AUDIT_CLASS_DIR_WRITE
#define AUDIT_CLASS_DIR_WRITE_32                     HM_AUDIT_CLASS_DIR_WRITE_32
#define AUDIT_CLASS_CHATTR                           HM_AUDIT_CLASS_CHATTR
#define AUDIT_CLASS_CHATTR_32                        HM_AUDIT_CLASS_CHATTR_32
#define AUDIT_CLASS_READ                             HM_AUDIT_CLASS_READ
#define AUDIT_CLASS_READ_32                          HM_AUDIT_CLASS_READ_32
#define AUDIT_CLASS_WRITE                            HM_AUDIT_CLASS_WRITE
#define AUDIT_CLASS_WRITE_32                         HM_AUDIT_CLASS_WRITE_32
#define AUDIT_CLASS_SIGNAL                           HM_AUDIT_CLASS_SIGNAL
#define AUDIT_CLASS_SIGNAL_32                        HM_AUDIT_CLASS_SIGNAL_32
#define AUDIT_BIT_MASK                               HM_AUDIT_BIT_MASK
#define AUDIT_LESS_THAN                              HM_AUDIT_LESS_THAN
#define AUDIT_GREATER_THAN                           HM_AUDIT_GREATER_THAN
#define AUDIT_NOT_EQUAL                              HM_AUDIT_NOT_EQUAL
#define AUDIT_EQUAL                                  HM_AUDIT_EQUAL
#define AUDIT_BIT_TEST                               HM_AUDIT_BIT_TEST
#define AUDIT_LESS_THAN_OR_EQUAL                     HM_AUDIT_LESS_THAN_OR_EQUAL
#define AUDIT_GREATER_THAN_OR_EQUAL                  HM_AUDIT_GREATER_THAN_OR_EQUAL
#define AUDIT_OPERATORS                              HM_AUDIT_OPERATORS
#define AUDIT_UNUSED_BITS                            HM_AUDIT_UNUSED_BITS
#define AUDIT_COMPARE_UID_TO_OBJ_UID                 HM_AUDIT_COMPARE_UID_TO_OBJ_UID
#define AUDIT_COMPARE_GID_TO_OBJ_GID                 HM_AUDIT_COMPARE_GID_TO_OBJ_GID
#define AUDIT_COMPARE_EUID_TO_OBJ_UID                HM_AUDIT_COMPARE_EUID_TO_OBJ_UID
#define AUDIT_COMPARE_EGID_TO_OBJ_GID                HM_AUDIT_COMPARE_EGID_TO_OBJ_GID
#define AUDIT_COMPARE_AUID_TO_OBJ_UID                HM_AUDIT_COMPARE_AUID_TO_OBJ_UID
#define AUDIT_COMPARE_SUID_TO_OBJ_UID                HM_AUDIT_COMPARE_SUID_TO_OBJ_UID
#define AUDIT_COMPARE_SGID_TO_OBJ_GID                HM_AUDIT_COMPARE_SGID_TO_OBJ_GID
#define AUDIT_COMPARE_FSUID_TO_OBJ_UID               HM_AUDIT_COMPARE_FSUID_TO_OBJ_UID
#define AUDIT_COMPARE_FSGID_TO_OBJ_GID               HM_AUDIT_COMPARE_FSGID_TO_OBJ_GID
#define AUDIT_COMPARE_UID_TO_AUID                    HM_AUDIT_COMPARE_UID_TO_AUID
#define AUDIT_COMPARE_UID_TO_EUID                    HM_AUDIT_COMPARE_UID_TO_EUID
#define AUDIT_COMPARE_UID_TO_FSUID                   HM_AUDIT_COMPARE_UID_TO_FSUID
#define AUDIT_COMPARE_UID_TO_SUID                    HM_AUDIT_COMPARE_UID_TO_SUID
#define AUDIT_COMPARE_AUID_TO_FSUID                  HM_AUDIT_COMPARE_AUID_TO_FSUID
#define AUDIT_COMPARE_AUID_TO_SUID                   HM_AUDIT_COMPARE_AUID_TO_SUID
#define AUDIT_COMPARE_AUID_TO_EUID                   HM_AUDIT_COMPARE_AUID_TO_EUID
#define AUDIT_COMPARE_EUID_TO_SUID                   HM_AUDIT_COMPARE_EUID_TO_SUID
#define AUDIT_COMPARE_EUID_TO_FSUID                  HM_AUDIT_COMPARE_EUID_TO_FSUID
#define AUDIT_COMPARE_SUID_TO_FSUID                  HM_AUDIT_COMPARE_SUID_TO_FSUID
#define AUDIT_COMPARE_GID_TO_EGID                    HM_AUDIT_COMPARE_GID_TO_EGID
#define AUDIT_COMPARE_GID_TO_FSGID                   HM_AUDIT_COMPARE_GID_TO_FSGID
#define AUDIT_COMPARE_GID_TO_SGID                    HM_AUDIT_COMPARE_GID_TO_SGID
#define AUDIT_COMPARE_EGID_TO_FSGID                  HM_AUDIT_COMPARE_EGID_TO_FSGID
#define AUDIT_COMPARE_EGID_TO_SGID                   HM_AUDIT_COMPARE_EGID_TO_SGID
#define AUDIT_COMPARE_SGID_TO_FSGID                  HM_AUDIT_COMPARE_SGID_TO_FSGID
#define AUDIT_MAX_FIELD_COMPARE                      HM_AUDIT_MAX_FIELD_COMPARE
#define AUDIT_STATUS_ENABLED                         HM_AUDIT_STATUS_ENABLED
#define AUDIT_STATUS_FAILURE                         HM_AUDIT_STATUS_FAILURE
#define AUDIT_STATUS_PID                             HM_AUDIT_STATUS_PID
#define AUDIT_STATUS_RATE_LIMIT                      HM_AUDIT_STATUS_RATE_LIMIT
#define AUDIT_STATUS_BACKLOG_LIMIT                   HM_AUDIT_STATUS_BACKLOG_LIMIT
#define AUDIT_STATUS_BACKLOG_WAIT_TIME               HM_AUDIT_STATUS_BACKLOG_WAIT_TIME
#define AUDIT_STATUS_LOST                            HM_AUDIT_STATUS_LOST
#define AUDIT_FEATURE_BITMAP_BACKLOG_LIMIT           HM_AUDIT_FEATURE_BITMAP_BACKLOG_LIMIT
#define AUDIT_FEATURE_BITMAP_BACKLOG_WAIT_TIME       HM_AUDIT_FEATURE_BITMAP_BACKLOG_WAIT_TIME
#define AUDIT_FEATURE_BITMAP_EXECUTABLE_PATH         HM_AUDIT_FEATURE_BITMAP_EXECUTABLE_PATH
#define AUDIT_FEATURE_BITMAP_EXCLUDE_EXTEND          HM_AUDIT_FEATURE_BITMAP_EXCLUDE_EXTEND
#define AUDIT_FEATURE_BITMAP_SESSIONID_FILTER        HM_AUDIT_FEATURE_BITMAP_SESSIONID_FILTER
#define AUDIT_FEATURE_BITMAP_LOST_RESET              HM_AUDIT_FEATURE_BITMAP_LOST_RESET
#define AUDIT_FEATURE_BITMAP_FILTER_FS               HM_AUDIT_FEATURE_BITMAP_FILTER_FS
#define AUDIT_FEATURE_BITMAP_ALL                     HM_AUDIT_FEATURE_BITMAP_ALL
#define AUDIT_FAIL_SILENT                            HM_AUDIT_FAIL_SILENT
#define AUDIT_FAIL_PRINTK                            HM_AUDIT_FAIL_PRINTK
#define AUDIT_FAIL_PANIC                             HM_AUDIT_FAIL_PANIC
#define ARM                                          HM_ARM
#define AARCH64                                      HM_AARCH64
#define AUDIT_ARCH_AARCH64                           HM_AUDIT_ARCH_AARCH64
#define AUDIT_ARCH_ARM                               HM_AUDIT_ARCH_ARM
#define AUDIT_ARCH_ARMEB                             HM_AUDIT_ARCH_ARMEB
#define AUDIT_PERM_EXEC                              HM_AUDIT_PERM_EXEC
#define AUDIT_PERM_WRITE                             HM_AUDIT_PERM_WRITE
#define AUDIT_PERM_READ                              HM_AUDIT_PERM_READ
#define AUDIT_PERM_ATTR                              HM_AUDIT_PERM_ATTR
#define AUDIT_TYPE_UNKNOWN                           HM_AUDIT_TYPE_UNKNOWN
#define AUDIT_TYPE_NORMAL                            HM_AUDIT_TYPE_NORMAL
#define AUDIT_TYPE_PARENT                            HM_AUDIT_TYPE_PARENT
#define AUDIT_TYPE_CHILD_DELETE                      HM_AUDIT_TYPE_CHILD_DELETE
#define AUDIT_TYPE_CHILD_CREATE                      HM_AUDIT_TYPE_CHILD_CREATE
#define AUDIT_MESSAGE_TEXT_MAX                       HM_AUDIT_MESSAGE_TEXT_MAX
#define AUDIT_NLGRP_MAX                              HM_AUDIT_NLGRP_MAX
#define AUDIT_OFF                                    HM_AUDIT_OFF
#define AUDIT_ON                                     HM_AUDIT_ON
#define AUDIT_LOCKED                                 HM_AUDIT_LOCKED
#define AUDIT_FEATURE_VERSION                        HM_AUDIT_FEATURE_VERSION
#define AUDIT_FEATURE_ONLY_UNSET_LOGINUID            HM_AUDIT_FEATURE_ONLY_UNSET_LOGINUID
#define AUDIT_FEATURE_LOGINUID_IMMUTABLE             HM_AUDIT_FEATURE_LOGINUID_IMMUTABLE
#define AUDIT_LAST_FEATURE                           HM_AUDIT_LAST_FEATURE
#define AUDIT_FEATURE_TO_MASK(x)                     HM_AUDIT_FEATURE_TO_MASK(x)
#define AUDIT_UID_UNSET                              HM_AUDIT_UID_UNSET
#define AUDIT_SID_UNSET                              HM_AUDIT_SID_UNSET
#define __AUDIT_ARCH_64BIT                           __HM_AUDIT_ARCH_64BIT
#define __AUDIT_ARCH_LE                              __HM_AUDIT_ARCH_LE

#define audit_feature_valid(x)		((x) >= 0 && (x) <= AUDIT_LAST_FEATURE)
#endif /* ULIBS_LIBAUDIT_AUDIT_H */
