# Copyright (C) Huawei Technologies Co., Ltd. 2021. All rights reserved.
# Description: Configure file for hmcmakeng GNU toolchain
# Author: Huawei OS Kernel Lab
# Create: Wed Mar 17 01:22:07 2021

# AUTO-GENERATED by aarch64-euler-elf-hm-cmake-toolchain-cross


set(CMAKE_SYSTEM_NAME Hongmeng)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

# Hack to make sub cmake inherit HMNATIVESDKPATH settings
if(NOT HMNATIVESDKPATH)
    set(HMNATIVESDKPATH "$ENV{__HMNATIVESDKPATH_ENV}")
endif()

# Force user to provide HMNATIVESDKPATH
if(NOT HMNATIVESDKPATH)
    message(FATAL_ERROR "HMNATIVESDKPATH must be set. Use 'cmake -DHMNATIVESDKPATH'.")
else()
    set(ENV{__HMNATIVESDKPATH_ENV} ${HMNATIVESDKPATH})
endif()

message(VERBOSE "Use hongmeng cross-compiling toolchain 'aarch64-euler-elf-'.")

set(CMAKE_C_COMPILER ${HMNATIVESDKPATH}/usr/bin/aarch64-euler-elf-gcc)
set(CMAKE_CXX_COMPILER ${HMNATIVESDKPATH}/usr/bin/aarch64-euler-elf-g++)
set(CMAKE_ASM_COMPILER ${HMNATIVESDKPATH}/usr/bin/aarch64-euler-elf-gcc)
set(CMAKE_AR ${HMNATIVESDKPATH}/usr/bin/aarch64-euler-elf-ar)

set(CMAKE_FIND_ROOT_PATH ${HMNATIVESDKPATH})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# toolchain will be loaded multiple times, for all states we should not simply append
# to them
if (NOT ("${HMNATIVESDKPATH}/usr/share/cmake/Modules" IN_LIST CMAKE_MODULE_PATH))
    list(APPEND CMAKE_MODULE_PATH "${HMNATIVESDKPATH}/usr/share/cmake/Modules")
endif()
if (NOT ("${CMAKE_SYSROOT}/usr/share/cmake/Modules" IN_LIST CMAKE_MODULE_PATH))
    # Set target dir so find module installed into target can be found
    list(APPEND CMAKE_MODULE_PATH "${CMAKE_SYSROOT}/usr/share/cmake/Modules")
endif()

if ("aarch64" STREQUAL "arm" OR "aarch64" STREQUAL "armeb")
    # This options comes from arch/arm/Makefile.main.arch which
    # should be turned off by Kconfig.
    if (NOT CMAKE_C_FLAGS_INIT_APPENDED)
        string(APPEND CMAKE_C_FLAGS_INIT " -fno-omit-frame-pointer -mapcs")
        set(CMAKE_C_FLAGS_INIT_APPENDED TRUE)
    endif()
endif()

# Set CMAKE_NO_SYSTEM_FROM_IMPORTED so imported libraries will have
# '-I' instead of '-isystem' before their interface include directories
# set(CMAKE_NO_SYSTEM_FROM_IMPORTED TRUE)

# vim: ts=4:sw=4:expandtab
