/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 *
 * Description:  Error codes for the FIPS
 *
 * Create: 2021/7/17
 * Version       : 1.0
 */

#ifndef FIPS_HEADER_H
#define FIPS_HEADER_H

#include <openssl/opensslconf.h>
#include <openssl/dsa.h>
#include <openssl/evp.h>
#include <openssl/bn.h>

#ifndef OPENSSL_NO_FIPS

# ifdef  __cplusplus
extern "C" {
# endif

# define FIPS_MODE_OFF 0
# define FIPS_MODE_ON  1
# define FIPS_SELFTEST_PASS 0
# define FIPS_SELFTEST_FAIL 1
/* BEGIN ERROR CODES */
/* The following lines are auto generated by the script mkerr.pl. Any changes
 * made after this point may be overwritten when the script is next run.
 */

/* Error codes for the FIPS functions. */

/* Function codes. */
# define FIPS_F_DH_BUILTIN_GENPARAMS                      100
# define FIPS_F_DSA_BUILTIN_PARAMGEN2                     107
# define FIPS_F_DSA_DO_SIGN                               102
# define FIPS_F_DSA_DO_VERIFY                             103
# define FIPS_F_ECDH_COMPUTE_KEY                          123
# define FIPS_F_FIPS_CHECK_DSA                            104
# define FIPS_F_FIPS_CHECK_EC                             142
# define FIPS_F_FIPS_CHECK_RSA                            106
# define FIPS_F_FIPS_MODULE_MODE_SET                      108
# define FIPS_F_FIPS_PKEY_SIGNATURE_TEST                  109
# define FIPS_F_FIPS_RSA_BUILTIN_KEYGEN                   101
# define FIPS_F_OSSL_ECDSA_SIGN_SIG                       143
# define FIPS_F_OSSL_ECDSA_VERIFY_SIG                     148
# define FIPS_F_RSA_OSSL_PRIVATE_DECRYPT                  117
# define FIPS_F_RSA_OSSL_PRIVATE_ENCRYPT                  118
# define FIPS_F_RSA_OSSL_PUBLIC_DECRYPT                   119
# define FIPS_F_RSA_OSSL_PUBLIC_ENCRYPT                   120
# define FIPS_F_PKEY_RSA_VERIFY                           153
# define FIPS_F_FIPS_HMAC_INIT_EX                         155
# define FIPS_F_FIPS_HMAC_SET_PRIV_KEY                    156
# define FIPS_F_FIPS_DRBG_RESEED                          140
# define FIPS_F_FIPS_DRBG_BYTES                           131
# define FIPS_F_FIPS_DRBG_GENERATE                        134
# define FIPS_F_FIPS_DRBG_SET                             135
# define FIPS_F_FIPS_DRBG_INSTANTIATE                     138
# define FIPS_F_FIPS_DRBG_NEW                             139
# define FIPS_F_FIPS_RAND_SET_METHOD                      126
# define FIPS_F_FIPS_RAND_SEED                            128
# define FIPS_F_FIPS_RAND_BYTES                           114
# define FIPS_F_FIPS_RAND_STATUS                          127
# define FIPS_F_FIPS_SELFTEST_RESULT                      157
# define FIPS_F_FIPS_DRBG_SINGLE_KAT                      141
# define FIPS_F_FIPS_DRBG_ERROR_CHECK                     136
# define FIPS_F_FIPS_DRBG_CHECK                           146

/* Reason codes. */
# define FIPS_R_FIPS_MODE_INVALID_PARAM                   103
# define FIPS_R_FIPS_SELFTEST_FAILED                      106
# define FIPS_R_GENERATE_ERROR                            137
# define FIPS_R_IN_ERROR_STATE                            123
# define FIPS_R_KEY_TOO_SHORT                             108
# define FIPS_R_NONCE_ERROR_UNDETECTED                    149
# define FIPS_R_PAIRWISE_TEST_FAILED                      107
# define FIPS_R_PERSONALISATION_ERROR_UNDETECTED          128
# define FIPS_R_PERSONALISATION_STRING_TOO_LONG           129
# define FIPS_R_REQUEST_LENGTH_ERROR_UNDETECTED           130
# define FIPS_R_REQUEST_TOO_LARGE_FOR_DRBG                131
# define FIPS_R_RESEED_COUNTER_ERROR                      132
# define FIPS_R_RESEED_ERROR                              133
# define FIPS_R_SELFTEST_FAILED                           101
# define FIPS_R_SELFTEST_FAILURE                          135
# define FIPS_R_TEST_FAILURE                              117
# define FIPS_R_UNSUPPORTED_DRBG_TYPE                     139
# define FIPS_R_VERIGY_SIGN_UNSUPPORTED_SHA1              154
# define FIPS_R_KEY_SIZE_TOO_SMALL                        156
# define FIPS_R_ERROR_INITIALISING_DRBG                   115
# define FIPS_R_DRBG_NOT_INITIALISED                      152
# define FIPS_R_ALREADY_INSTANTIATED                      134
# define FIPS_R_ERROR_RETRIEVING_ENTROPY                  122
# define FIPS_R_ERROR_RETRIEVING_NONCE                    140
# define FIPS_R_ERROR_INSTANTIATING_DRBG                  127
# define FIPS_R_NOT_INSTANTIATED                          126
# define FIPS_R_ADDITIONAL_INPUT_TOO_LONG                 125
# define FIPS_R_ERROR_RETRIEVING_ADDITIONAL_INPUT         124
# define FIPS_R_NON_FIPS_METHOD                           100
# define FIPS_R_FIPS_SELFTEST_INVALID_PARAM               157
# define FIPS_R_NOPR_TEST1_FAILURE                        145
# define FIPS_R_NOPR_TEST2_FAILURE                        146
# define FIPS_R_PR_TEST1_FAILURE                          147
# define FIPS_R_PR_TEST2_FAILURE                          148
# define FIPS_R_ENTROPY_ERROR_UNDETECTED                  104
# define FIPS_R_GENERATE_ERROR_UNDETECTED                 118
# define FIPS_R_UNINSTANTIATE_ERROR                       141
# define FIPS_R_ADDITIONAL_INPUT_ERROR_UNDETECTED         150
# define FIPS_R_ENTROPY_NOT_REQUESTED_FOR_RESEED          105
# define FIPS_R_UNINSTANTIATE_ZEROISE_ERROR               138

# ifdef  __cplusplus
}
# endif
#endif // OPENSSL_NO_FIPS

#endif // FIPS_HEADER_H
