/*
 * Copyright (C) Huawei Technologies Co., Ltd. 2020. All rights reserved.
 * Author: Huawei Dresden Research Center
 * Create: Wed 22 Jan 2020 01:02:52 PM CET
 */

/* In low-level software, stdint.h is sometimes not available.
 * This file is supposed to give an example on how to use libvsync with
 * types like: u8, u16,...
*/

//Example:
//#include the u* type definition here
//#define vuint8_t  u8
//#define vuint16_t u16
//#define vuint32_t u32
//#define vuint64_t u64
