/*
 *
 * Automatically generated file; DO NOT EDIT.
 * Main menu
 *
 */
#define CONFIG_FSLIB_SERVER_INFO_LIST_SIZE 8
#define CONFIG_HMBUILD_INSTALL_DIR_MANDIR "/usr/share/man"
#define CONFIG_HMBUILD_OUTPUT_SUFFIX ""
#define CONFIG_HMBUILD_FINDPATH_INCLUDE "include"
#define CONFIG_HMBUILD_INSTALL_DIR_DATADIR "/usr/share"
#define CONFIG_HMBUILD_INSTALL_DIR_BASE_BINDIR "/bin"
#define CONFIG_HMBUILD_INSTALL_DIR_BASE_SBINDIR "/sbin"
#define CONFIG_HMBUILD_STRIP_OPTION "--strip-unneeded"
#define CONFIG_HMBUILD_INSTALL_DIR_BINDIR "/usr/bin"
#define CONFIG_HMBUILD_INSTALL_DIR_PREFIX "/usr"
#define CONFIG_HMBUILD_INSTALL_DIR_NONARCH_LIBDIR "/usr/lib"
#define CONFIG_HMBUILD_INSTALL_DIR_LIBDIR "/usr/lib"
#define CONFIG_HMBUILD_INSTALL_DIR_EXEC_PREFIX "/usr"
#define CONFIG_HMBUILD_FINDPATH_LIB "lib"
#define CONFIG_HMBUILD_INSTALL_DIR_LIBEXECDIR "/usr/libexec"
#define CONFIG_FSLIB_GFD_TABLE 1
#define CONFIG_HMBUILD_INSTALL_DIR_NONARCH_BASE_LIBDIR "/lib"
#define CONFIG_FSLIB_TRANSFER_FD 1
#define CONFIG_HMBUILD_MAKE_HEADERS 1
#define CONFIG_HMBUILD_KCONFIG_INCLUDED 1
#define CONFIG_HMBUILD_INSTALL_DIR_DOCDIR "/usr/share/doc"
#define CONFIG_HMBUILD_INSTALL_DIR_INFODIR "/usr/share/info"
#define CONFIG_HMBUILD_HMFINDUTILS_CONF ""
#define CONFIG_HMBUILD_INSTALL_DIR_CONFDIR "/etc"
#define CONFIG_FSLIB_MAX_OPEN_FILES 1048576
#define CONFIG_HMBUILD_INSTALL_DIR_BASE_LIBDIR "/lib"
#define CONFIG_HMBUILD_INSTALL_DIR_SBINDIR "/usr/sbin"
#define CONFIG_HMBUILD_EXTRA_CFLAGS ""
#define CONFIG_HMBUILD_EXTRA_CFLAGS_BASE "      -fstack-protector-strong      -O2 -pipe "
#define CONFIG_HMBUILD_PROFILE_RELEASE 1
#define CONFIG_HMBUILD_EXTRA_LDFLAGS_BASE "      -Wl,-z,relro     -Wl,-z,now     -Wl,-z,noexecstack     -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed"
#define CONFIG_HMBUILD_DEPENDENCY_SUFFIX ""
#define CONFIG_FSLIB_DEFAULT_OPEN_FILES 1024
#define CONFIG_HMBUILD_INSTALL_DIR_INCLUDEDIR "/usr/include"
#define CONFIG_HMBUILD_TOOLCHAIN_GNU 1
#define CONFIG_FSLIB_AUDIT 1
#define CONFIG_HMBUILD_RANDOM_NUMBER 0x890d5b3342b75178
#define CONFIG_HMBUILD_EXTRA_LDFLAGS ""
