/*
 * Copyright (C) Huawei Technologies Co., Ltd. 2018-2020. All rights reserved.
 * Description: Definition of sysconf
 * Author: Huawei OS Kernel Lab
 * Create: Sat Nov 24 17:26:52 2018
 */
#ifndef UAPI_HMKERNEL_SYSCONF_H
#define UAPI_HMKERNEL_SYSCONF_H

#include <asm/sysconf.h>

enum {
	__SYSCONF_KERNEL_RELEASE = __SYSCONF_ARCH_MAX,
	__SYSCONF_HARDWARE_PLATFORM,
	__SYSCONF_MACHINE,
	__SYSCONF_CONFIG_CPU,
	__SYSCONF_REGISTER_CPU,
	__SYSCONF_REGISTER_CPU_MASK,
	__SYSCONF_ONLINE_CPU,
	__SYSCONF_ONLINE_CPU_MASK,
	__SYSCONF_CPU_CAPACITY,
	__SYSCONF_CLOCK_FREQ,
	__SYSCONF_DTB_SIZE,
	__SYSCONF_CONFIG_TIMER,
	__SYSCONF_CONFIG_PMU,
	__SYSCONF_HW_DEBUG,
	__SYSCONF_RESPART_NODE_NUM,
	__SYSCONF_RESPART_NODE_INFO,
	__SYSCONF_PE_MAIN_ID,
	__SYSCONF_CSPACE_SLOTS,
	__SYSCONF_CONFIG_HYPERVISOR,
	__SYSCONF_CONFIG_MODULE_SCHED_CLASS,
	__SYSCONF_MAX,
};

#define __SYSCONF_STR_LEN_MAX 64

#define __TIMER_TIMEWHEEL  "timewheel"
#define __TIMER_RBTREE     "timer_rbt"

#endif
