/*
 * Copyright (C) Huawei Technologies Co., Ltd. 2018-2021. All rights reserved.
 * Description: Definition of errno
 * Author: Huawei OS Kernel Lab
 * Create: Thu Sep 13 03:39:49 2018
 */

#ifndef UAPI_HMKERNEL_ERRNO_COMMOM_H
#define UAPI_HMKERNEL_ERRNO_COMMOM_H

#if !defined(HM_EDEF) || !defined(HM_EDEF_P)
# error This file should not be directly included
#endif

/*
 * Use HM_EDEF_P if the hm errno has corresponding POSIX errno,
 * use HM_EDEF if otherwise.
 */
HM_EDEF  (E_HM_OK,		0,		"SUCCESS")
HM_EDEF_P(E_HM_EXIST,		EEXIST,		"E_HM_EXIST")
HM_EDEF_P(E_HM_FAULT,		EFAULT,		"E_HM_FAULT")
HM_EDEF_P(E_HM_NOENT,		ENOENT,		"E_HM_NOENT")
HM_EDEF_P(E_HM_INVAL,		EINVAL,		"E_HM_INVAL")
HM_EDEF  (E_HM_ALIGN,		EHMERROR,	"E_HM_ALIGN")
HM_EDEF_P(E_HM_OVERFLOW,	EOVERFLOW,	"E_HM_OVERFLOW")
HM_EDEF  (E_HM_FAULT_SRC,	EHMERROR,	"E_HM_FAULT_SRC")
HM_EDEF  (E_HM_FAULT_DST,	EHMERROR,	"E_HM_FAULT_DST")
HM_EDEF_P(E_HM_PERM,		EPERM,		"E_HM_PERM")
HM_EDEF  (E_HM_DEAD,		EHMERROR,	"E_HM_DEAD")
HM_EDEF_P(E_HM_INTR,		EINTR,		"E_HM_INTR")
HM_EDEF_P(E_HM_NOMEM,		ENOMEM,		"E_HM_NOMEM")
HM_EDEF_P(E_HM_AGAIN,		EAGAIN,		"E_HM_AGAIN")
HM_EDEF  (E_HM_IDLE,		EHMERROR,	"E_HM_IDLE")
HM_EDEF_P(E_HM_NOEXEC,		ENOEXEC,	"E_HM_NOEXEC")
HM_EDEF  (E_HM_TOOMANY,		EHMERROR,	"E_HM_TOOMANY")
HM_EDEF_P(E_HM_NOSYS,		ENOSYS,		"E_HM_NOSYS")
HM_EDEF_P(E_HM_SRCH,		ESRCH,		"E_HM_SRCH")
HM_EDEF_P(E_HM_CHILD,		ECHILD,		"E_HM_CHILD")
HM_EDEF_P(E_HM_IO,		EIO,		"E_HM_IO")
HM_EDEF_P(E_HM_BUSY,		EBUSY,		"E_HM_BUSY")
HM_EDEF_P(E_HM_TIMEDOUT,	ETIMEDOUT,	"E_HM_TIMEDOUT")
HM_EDEF_P(E_HM_DEADLK,		EDEADLK,	"E_HM_DEADLK")
HM_EDEF  (E_HM_HMSIGINTR,	EHMERROR,	"E_HM_HMSIGINTR")
HM_EDEF  (E_HM_TRIGGER_STATE,	EHMERROR,	"E_HM_TRIGGER_STATE")
HM_EDEF  (E_HM_TRIGGER_NO_CURR,	EHMERROR,	"E_HM_TRIGGER_NO_CURR")
HM_EDEF  (E_HM_PAGE_IN_USE,	EHMERROR,	"E_HM_PAGE_IN_USE")
HM_EDEF  (E_HM_PAGE_SRC_STATE,	EHMERROR,	"E_HM_PAGE_SRC_STATE")
HM_EDEF  (E_HM_PAGE_DST_STATE,	EHMERROR,	"E_HM_PAGE_DST_STATE")
HM_EDEF  (E_HM_NON_UNIFORM,	EHMERROR,	"E_HM_NON_UNIFORM")
HM_EDEF  (E_HM_FORMAT,		EHMERROR,	"E_HM_FORMAT")
HM_EDEF  (E_HM_INCONSISTENT,	EHMERROR,	"E_HM_INCONSISTENT")
HM_EDEF  (E_HM_TAILCALL,	EHMERROR,	"E_HM_TAILCALL")
HM_EDEF_P(E_HM_PIPE,		EPIPE,		"E_HM_PIPE")

HM_EDEF  (E_HM_KERNEL_MAX,	EHMERROR,	"E_HM_KERNEL_MAX")

#undef UAPI_HMKERNEL_ERRNO_COMMOM_H
#endif
