/*
 * Copyright (C) Huawei Technologies Co., Ltd. 2021. All rights reserved.
 * Description: pekse calls declaring
 * Author: Huawei OS Kernel Lab
 * Create: Mon Feb 22 10:32:19 2021
 */

#ifndef UAPI_PEKSE_CALLS__H
#define UAPI_PEKSE_CALLS__H

#define	PEKSE_CMD_VMCTL_CREATE			0xc0087300UL
#define	PEKSE_CMD_VMCTL_DESTROY			0xc0087301UL
#define	PEKSE_CMD_VMCTL_QUERYONE		0xc0087302UL
#define	PEKSE_CMD_VMCTL_QUERYALL		0xc0087303UL
#define	PEKSE_CMD_VMCTL_SUSPEND			0xc0087304UL
#define	PEKSE_CMD_VMCTL_RESUME			0xc0087305UL
#define	PEKSE_CMD_VMCTL_RESTART			0xc0087306UL
#define	PEKSE_CMD_MEMORY_ADD			0xc0087307UL
#define	PEKSE_CMD_MEMORY_REMOVE			0xc0087308UL
#define	PEKSE_CMD_CPU_ADD			0xc0087309UL
#define	PEKSE_CMD_CPU_REMOVE			0xc008730aUL
#define	PEKSE_CMD_VMCTL_SCHED_OUT		0xc008730dUL
#define	PEKSE_CMD_MMAP_SHARED_MEMORY		0xc008730eUL
#define	PEKSE_CMD_MUNMAP_SHARED_MEMORY		0xc008730fUL
#define	PEKSE_CMD_MNTN_DUMP_VMMEMORY		0xc0087310UL
#define	PEKSE_CMD_IRQ_ALLOCATE			0xc0087311UL
#define	PEKSE_CMD_IRQ_RELEASE			0xc0087312UL
#define	PEKSE_CMD_IRQ_DUMP			0xc0087313UL
#define	PEKSE_CMD_HKIP_CODE_PROTECT_DISABLE	0xc0087314UL
#define	PEKSE_CMD_HKIP_CODE_PROTECT_ENABLE	0xc0087315UL
#define	PEKSE_CMD_HKIP_CODE_PROTECT_STATUS	0xc0087316UL
#define	PEKSE_CMD_STATIC_SHARED_MEMORY_WRITE	0xc0087317UL
#define	PEKSE_CMD_STATIC_SHARED_MEMORY_READ	0xc0087318UL
#define	PEKSE_CMD_VMCTL_FORCE_DELETE		0xc0087319UL
#define	PEKSE_CMD_VMCTL_SET_DATE_TIME		0xc008731aUL
#define	PEKSE_CMD_LAUNCH_DP_PEK			0xc008731bUL

#define PEKSE_CMD_HKIPLOG_ALLOCATE		0xFF2B0099UL
#define PEKSE_CMD_HKIPLOG_SWITCH_OPEN		0xFF2B009AUL
#define PEKSE_CMD_HKIPLOG_SWITCH_CLOSE		0xFF2B009BUL

/* CMD id defined by Hongmeng */
#define	PEKSE_CMD_MNTN_GET_PA			0xd0000000UL

#define PEKSE_HYPERCALL_MEMORY_OP		1
#define PEKSE_HYPERCALL_VMCTL_OP		2
#define PEKSE_HYPERCALL_PHYSDEV_OP		3
#define PEKSE_HYPERCALL_CPU_OP			4
#define PEKSE_HYPERCALL_SCHED_OP		5
#define PEKSE_HYPERCALL_MNTN_OP			6
#define PEKSE_HYPERCALL_IRQ_OP			7
#define PEKSE_HYPERCALL_HKIP_OP			9
#define PEKSE_HYPERCALL_HKIPLOG_OP		10

#define PEKSE_CTRL_CREATE			1
#define PEKSE_CTRL_REMOVE			2
#define PEKSE_CTRL_QUERYONE			3
#define PEKSE_CTRL_QUERYALL			4
#define PEKSE_CTRL_FORCE_REMOVE			5

#define PEKSE_MEMORY_RESERVED			1
#define PEKSE_MEMORY_REMOVED			2
#define PEKSE_MMAP_SHARED_MEMORY		3
#define PEKSE_MUNMAP_SHARED_MEMORY		4

#define PEKSE_CPU_RESERVED			1
#define PEKSE_CPU_REMOVED			2

#define PEKSE_SCHED_OUT				1

#define PEKSE_HKIP_CODE_PROTECT_DISABLE		1
#define PEKSE_HKIP_CODE_PROTECT_ENABLE		2
#define PEKSE_HKIP_CODE_PROTECT_STATUS		3

#define PEKSE_HKIPLOG_ALLOCATE			1
#define PEKSE_HKIPLOG_SWITCH_OPEN		2
#define PEKSE_HKIPLOG_SWITCH_CLOSE		3

#define PEKSE_PHYSDEV_ADD			1
#define PEKSE_PHYSDEV_REMOVE			2

#define PEKSE_MNTN_LOG				1
#define PEKSE_MNTN_DUMP_VMMEMORY		2
#define PEKSE_MNTN_SET_DATE_TIME		3
#define PEKSE_MNTN_GET_PA			4

#define PEKSE_IRQ_ALLOCATE			1
#define PEKSE_IRQ_RELEASE			2
#define PEKSE_IRQ_DUMP				3

#define PEKSE_DP_KERNEL_INST			1
#define PEKSE_DP_APP_INST			2
#define PEKSE_DP_NOTIFY_PALTFORM		3
#define PEKSE_DP_BRINGUP_SECONDARY		4
#define PEKSE_DP_POWER_OFF			5

#define PEKSE_PEK_LAUNCH_DP			1

/* boot alloc 4K size buf for pek driver to transfer data */
#define MAX_USER_BUFFER				0x1000U

struct arm_smccc_res {
	unsigned long a0;
	unsigned long a1;
	unsigned long a2;
	unsigned long a3;
};

struct pekse_params {
	char buffer[MAX_USER_BUFFER];
};

struct pekse_call_result {
	u32 result;
};
#endif
