
#ifdef  __cplusplus
extern "C" {
#endif

#define    BN_abs_is_word                    HICRYPTO_BN_abs_is_word
#define    BN_add                            HICRYPTO_BN_add
#define    BN_add_word                       HICRYPTO_BN_add_word
#define    bn_add_words                      HICRYPTO_bn_add_words
#define    BN_asc2bn                         HICRYPTO_BN_asc2bn
#define    BN_bin2bn                         HICRYPTO_BN_bin2bn
#define    BN_BLINDING_convert               HICRYPTO_BN_BLINDING_convert
#define    BN_BLINDING_convert_ex            HICRYPTO_BN_BLINDING_convert_ex
#define    BN_BLINDING_create_param          HICRYPTO_BN_BLINDING_create_param
#define    BN_BLINDING_free                  HICRYPTO_BN_BLINDING_free
#define    BN_BLINDING_get_flags             HICRYPTO_BN_BLINDING_get_flags
#define    BN_BLINDING_invert                HICRYPTO_BN_BLINDING_invert
#define    BN_BLINDING_invert_ex             HICRYPTO_BN_BLINDING_invert_ex
#define    BN_BLINDING_is_current_thread     HICRYPTO_BN_BLINDING_is_current_thread
#define    BN_BLINDING_lock                  HICRYPTO_BN_BLINDING_lock
#define    BN_BLINDING_new                   HICRYPTO_BN_BLINDING_new
#define    BN_BLINDING_set_current_thread    HICRYPTO_BN_BLINDING_set_current_thread
#define    BN_BLINDING_set_flags             HICRYPTO_BN_BLINDING_set_flags
#define    BN_BLINDING_unlock                HICRYPTO_BN_BLINDING_unlock
#define    BN_BLINDING_update                HICRYPTO_BN_BLINDING_update
#define    BN_bn2bin                         HICRYPTO_BN_bn2bin
#define    BN_bn2binpad                      HICRYPTO_BN_bn2binpad
#define    BN_bn2dec                         HICRYPTO_BN_bn2dec
#define    BN_bn2hex                         HICRYPTO_BN_bn2hex
#define    BN_bn2lebinpad                    HICRYPTO_BN_bn2lebinpad
#define    BN_bntest_rand                    HICRYPTO_BN_bntest_rand
#define    BN_clear                          HICRYPTO_BN_clear
#define    BN_clear_bit                      HICRYPTO_BN_clear_bit
#define    BN_clear_free                     HICRYPTO_BN_clear_free
#define    BN_cmp                            HICRYPTO_BN_cmp
#define    bn_cmp_part_words                 HICRYPTO_bn_cmp_part_words
#define    bn_cmp_words                      HICRYPTO_bn_cmp_words
#define    BN_consttime_swap                 HICRYPTO_BN_consttime_swap
#define    BN_copy                           HICRYPTO_BN_copy
#define    bn_correct_top                    HICRYPTO_bn_correct_top
#define    BN_CTX_end                        HICRYPTO_BN_CTX_end
#define    BN_CTX_free                       HICRYPTO_BN_CTX_free
#define    BN_CTX_get                        HICRYPTO_BN_CTX_get
#define    BN_CTX_new                        HICRYPTO_BN_CTX_new
#define    BN_CTX_secure_new                 HICRYPTO_BN_CTX_secure_new
#define    BN_CTX_start                      HICRYPTO_BN_CTX_start
#define    BN_dec2bn                         HICRYPTO_BN_dec2bn
#define    BN_div                            HICRYPTO_BN_div
#define    bn_div_fixed_top                  HICRYPTO_bn_div_fixed_top
#define    BN_div_recp                       HICRYPTO_BN_div_recp
#define    BN_div_word                       HICRYPTO_BN_div_word
#define    bn_div_words                      HICRYPTO_bn_div_words
#define    BN_dup                            HICRYPTO_BN_dup
#define    BN_exp                            HICRYPTO_BN_exp
#define    bn_expand                         HICRYPTO_bn_expand
#define    bn_expand_internal                HICRYPTO_bn_expand_internal
#define    bn_expand2                        HICRYPTO_bn_expand2
#define    BN_free                           HICRYPTO_BN_free
#define    bn_free_d                         HICRYPTO_bn_free_d
#define    bn_from_mont_fixed_top            HICRYPTO_bn_from_mont_fixed_top
#define    BN_from_montgomery                HICRYPTO_BN_from_montgomery
#define    bn_from_montgomery_word           HICRYPTO_bn_from_montgomery_word
#define    BN_gcd                            HICRYPTO_BN_gcd
#define    BN_GENCB_call                     HICRYPTO_BN_GENCB_call
#define    BN_GENCB_free                     HICRYPTO_BN_GENCB_free
#define    BN_GENCB_get_arg                  HICRYPTO_BN_GENCB_get_arg
#define    BN_GENCB_new                      HICRYPTO_BN_GENCB_new
#define    BN_GENCB_set                      HICRYPTO_BN_GENCB_set
#define    BN_GENCB_set_old                  HICRYPTO_BN_GENCB_set_old
#define    BN_generate_prime_ex              HICRYPTO_BN_generate_prime_ex
#define    bn_get_bits                       HICRYPTO_bn_get_bits
#define    BN_get_flags                      HICRYPTO_BN_get_flags
#define    BN_get_word                       HICRYPTO_BN_get_word
#define    BN_hex2bn                         HICRYPTO_BN_hex2bn
#define    bn_init                           HICRYPTO_bn_init
#define    BN_is_bit_set                     HICRYPTO_BN_is_bit_set
#define    BN_is_negative                    HICRYPTO_BN_is_negative
#define    BN_is_odd                         HICRYPTO_BN_is_odd
#define    BN_is_one                         HICRYPTO_BN_is_one
#define    BN_is_prime_ex                    HICRYPTO_BN_is_prime_ex
#define    BN_is_prime_fasttest_ex           HICRYPTO_BN_is_prime_fasttest_ex
#define    BN_is_word                        HICRYPTO_BN_is_word
#define    BN_is_zero                        HICRYPTO_BN_is_zero
#define    BN_kronecker                      HICRYPTO_BN_kronecker
#define    BN_lebin2bn                       HICRYPTO_BN_lebin2bn
#define    bn_left_align                     HICRYPTO_bn_left_align
#define    BN_lshift                         HICRYPTO_BN_lshift
#define    bn_lshift_fixed_top               HICRYPTO_bn_lshift_fixed_top
#define    BN_lshift1                        HICRYPTO_BN_lshift1
#define    BN_mask_bits                      HICRYPTO_BN_mask_bits
#define    BN_mod_add                        HICRYPTO_BN_mod_add
#define    bn_mod_add_fixed_top              HICRYPTO_bn_mod_add_fixed_top
#define    BN_mod_add_quick                  HICRYPTO_BN_mod_add_quick
#define    BN_mod_exp                        HICRYPTO_BN_mod_exp
#define    BN_mod_exp_mont                   HICRYPTO_BN_mod_exp_mont
#define    BN_mod_exp_mont_consttime         HICRYPTO_BN_mod_exp_mont_consttime
#define    BN_mod_exp_mont_word              HICRYPTO_BN_mod_exp_mont_word
#define    BN_mod_exp_recp                   HICRYPTO_BN_mod_exp_recp
#define    BN_mod_exp_simple                 HICRYPTO_BN_mod_exp_simple
#define    BN_mod_exp2_mont                  HICRYPTO_BN_mod_exp2_mont
#define    BN_mod_inverse                    HICRYPTO_BN_mod_inverse
#define    BN_mod_inverse_no_branch          HICRYPTO_BN_mod_inverse_no_branch
#define    BN_mod_lshift                     HICRYPTO_BN_mod_lshift
#define    BN_mod_lshift_quick               HICRYPTO_BN_mod_lshift_quick
#define    BN_mod_lshift1                    HICRYPTO_BN_mod_lshift1
#define    BN_mod_lshift1_quick              HICRYPTO_BN_mod_lshift1_quick
#define    BN_mod_mul                        HICRYPTO_BN_mod_mul
#define    BN_mod_mul_montgomery             HICRYPTO_BN_mod_mul_montgomery
#define    BN_mod_mul_reciprocal             HICRYPTO_BN_mod_mul_reciprocal
#define    BN_mod_sqr                        HICRYPTO_BN_mod_sqr
#define    BN_mod_sqrt                       HICRYPTO_BN_mod_sqrt
#define    BN_mod_sub                        HICRYPTO_BN_mod_sub
#define    bn_mod_sub_fixed_top              HICRYPTO_bn_mod_sub_fixed_top
#define    BN_mod_sub_quick                  HICRYPTO_BN_mod_sub_quick
#define    BN_mod_word                       HICRYPTO_BN_mod_word
#define    BN_MONT_CTX_copy                  HICRYPTO_BN_MONT_CTX_copy
#define    BN_MONT_CTX_free                  HICRYPTO_BN_MONT_CTX_free
#define    BN_MONT_CTX_init                  HICRYPTO_BN_MONT_CTX_init
#define    BN_MONT_CTX_new                   HICRYPTO_BN_MONT_CTX_new
#define    BN_MONT_CTX_set                   HICRYPTO_BN_MONT_CTX_set
#define    BN_MONT_CTX_set_locked            HICRYPTO_BN_MONT_CTX_set_locked
#define    BN_mul                            HICRYPTO_BN_mul
#define    bn_mul_add_words                  HICRYPTO_bn_mul_add_words
#define    bn_mul_comba4                     HICRYPTO_bn_mul_comba4
#define    bn_mul_comba8                     HICRYPTO_bn_mul_comba8
#define    bn_mul_fixed_top                  HICRYPTO_bn_mul_fixed_top
#define    bn_mul_low_normal                 HICRYPTO_bn_mul_low_normal
#define    bn_mul_low_recursive              HICRYPTO_bn_mul_low_recursive
#define    bn_mul_mont                       HICRYPTO_bn_mul_mont
#define    bn_mul_mont_fixed_top             HICRYPTO_bn_mul_mont_fixed_top
#define    bn_mul_normal                     HICRYPTO_bn_mul_normal
#define    bn_mul_part_recursive             HICRYPTO_bn_mul_part_recursive
#define    bn_mul_recursive                  HICRYPTO_bn_mul_recursive
#define    BN_mul_word                       HICRYPTO_BN_mul_word
#define    bn_mul_words                      HICRYPTO_bn_mul_words
#define    BN_new                            HICRYPTO_BN_new
#define    BN_nnmod                          HICRYPTO_BN_nnmod
#define    BN_num_bits                       HICRYPTO_BN_num_bits
#define    bn_num_bits_consttime             HICRYPTO_bn_num_bits_consttime
#define    BN_num_bits_word                  HICRYPTO_BN_num_bits_word
#define    BN_POOL_finish                    HICRYPTO_BN_POOL_finish
#define    BN_POOL_get                       HICRYPTO_BN_POOL_get
#define    BN_POOL_init                      HICRYPTO_BN_POOL_init
#define    BN_POOL_release                   HICRYPTO_BN_POOL_release
#define    BN_priv_rand                      HICRYPTO_BN_priv_rand
#define    BN_priv_rand_range                HICRYPTO_BN_priv_rand_range
#define    BN_pseudo_rand                    HICRYPTO_BN_pseudo_rand
#define    BN_pseudo_rand_range              HICRYPTO_BN_pseudo_rand_range
#define    BN_rand                           HICRYPTO_BN_rand
#define    BN_rand_range                     HICRYPTO_BN_rand_range
#define    BN_reciprocal                     HICRYPTO_BN_reciprocal
#define    BN_RECP_CTX_free                  HICRYPTO_BN_RECP_CTX_free
#define    BN_RECP_CTX_init                  HICRYPTO_BN_RECP_CTX_init
#define    BN_RECP_CTX_new                   HICRYPTO_BN_RECP_CTX_new
#define    BN_RECP_CTX_set                   HICRYPTO_BN_RECP_CTX_set
#define    BN_rshift                         HICRYPTO_BN_rshift
#define    bn_rshift_fixed_top               HICRYPTO_bn_rshift_fixed_top
#define    BN_rshift1                        HICRYPTO_BN_rshift1
#define    BN_secure_new                     HICRYPTO_BN_secure_new
#define    BN_security_bits                  HICRYPTO_BN_security_bits
#define    BN_set_bit                        HICRYPTO_BN_set_bit
#define    BN_set_flags                      HICRYPTO_BN_set_flags
#define    BN_set_negative                   HICRYPTO_BN_set_negative
#define    BN_set_word                       HICRYPTO_BN_set_word
#define    BN_sqr                            HICRYPTO_BN_sqr
#define    bn_sqr_comba4                     HICRYPTO_bn_sqr_comba4
#define    bn_sqr_comba8                     HICRYPTO_bn_sqr_comba8
#define    bn_sqr_fixed_top                  HICRYPTO_bn_sqr_fixed_top
#define    bn_sqr_normal                     HICRYPTO_bn_sqr_normal
#define    bn_sqr_recursive                  HICRYPTO_bn_sqr_recursive
#define    bn_sqr_words                      HICRYPTO_bn_sqr_words
#define    BN_STACK_finish                   HICRYPTO_BN_STACK_finish
#define    BN_STACK_init                     HICRYPTO_BN_STACK_init
#define    BN_STACK_pop                      HICRYPTO_BN_STACK_pop
#define    BN_STACK_push                     HICRYPTO_BN_STACK_push
#define    BN_sub                            HICRYPTO_BN_sub
#define    bn_sub_part_words                 HICRYPTO_bn_sub_part_words
#define    BN_sub_word                       HICRYPTO_BN_sub_word
#define    bn_sub_words                      HICRYPTO_bn_sub_words
#define    BN_swap                           HICRYPTO_BN_swap
#define    bn_to_mont_fixed_top              HICRYPTO_bn_to_mont_fixed_top
#define    BN_to_montgomery                  HICRYPTO_BN_to_montgomery
#define    BN_uadd                           HICRYPTO_BN_uadd
#define    BN_ucmp                           HICRYPTO_BN_ucmp
#define    BN_usub                           HICRYPTO_BN_usub
#define    BN_value_one                      HICRYPTO_BN_value_one
#define    bn_wexpand                        HICRYPTO_bn_wexpand
#define    BN_with_flags                     HICRYPTO_BN_with_flags
#define    BN_zero_ex                        HICRYPTO_BN_zero_ex
#define    CRYPTO_128_unwrap                 HICRYPTO_CRYPTO_128_unwrap
#define    CRYPTO_128_unwrap_pad             HICRYPTO_CRYPTO_128_unwrap_pad
#define    CRYPTO_128_wrap                   HICRYPTO_CRYPTO_128_wrap
#define    CRYPTO_128_wrap_pad               HICRYPTO_CRYPTO_128_wrap_pad
#define    CRYPTO_cbc128_decrypt             HICRYPTO_CRYPTO_cbc128_decrypt
#define    CRYPTO_cbc128_encrypt             HICRYPTO_CRYPTO_cbc128_encrypt
#define    CRYPTO_ccm128_aad                 HICRYPTO_CRYPTO_ccm128_aad
#define    CRYPTO_ccm128_decrypt             HICRYPTO_CRYPTO_ccm128_decrypt
#define    CRYPTO_ccm128_decrypt_ccm64       HICRYPTO_CRYPTO_ccm128_decrypt_ccm64
#define    CRYPTO_ccm128_encrypt             HICRYPTO_CRYPTO_ccm128_encrypt
#define    CRYPTO_ccm128_encrypt_ccm64       HICRYPTO_CRYPTO_ccm128_encrypt_ccm64
#define    CRYPTO_ccm128_init                HICRYPTO_CRYPTO_ccm128_init
#define    CRYPTO_ccm128_setiv               HICRYPTO_CRYPTO_ccm128_setiv
#define    CRYPTO_ccm128_tag                 HICRYPTO_CRYPTO_ccm128_tag
#define    CRYPTO_cfb128_1_encrypt           HICRYPTO_CRYPTO_cfb128_1_encrypt
#define    CRYPTO_cfb128_8_encrypt           HICRYPTO_CRYPTO_cfb128_8_encrypt
#define    CRYPTO_cfb128_encrypt             HICRYPTO_CRYPTO_cfb128_encrypt
#define    CRYPTO_ctr128_encrypt             HICRYPTO_CRYPTO_ctr128_encrypt
#define    CRYPTO_ctr128_encrypt_ctr32       HICRYPTO_CRYPTO_ctr128_encrypt_ctr32
#define    CRYPTO_cts128_decrypt             HICRYPTO_CRYPTO_cts128_decrypt
#define    CRYPTO_cts128_decrypt_block       HICRYPTO_CRYPTO_cts128_decrypt_block
#define    CRYPTO_cts128_encrypt             HICRYPTO_CRYPTO_cts128_encrypt
#define    CRYPTO_cts128_encrypt_block       HICRYPTO_CRYPTO_cts128_encrypt_block
#define    CRYPTO_gcm128_aad                 HICRYPTO_CRYPTO_gcm128_aad
#define    CRYPTO_gcm128_decrypt             HICRYPTO_CRYPTO_gcm128_decrypt
#define    CRYPTO_gcm128_decrypt_ctr32       HICRYPTO_CRYPTO_gcm128_decrypt_ctr32
#define    CRYPTO_gcm128_encrypt             HICRYPTO_CRYPTO_gcm128_encrypt
#define    CRYPTO_gcm128_encrypt_ctr32       HICRYPTO_CRYPTO_gcm128_encrypt_ctr32
#define    CRYPTO_gcm128_finish              HICRYPTO_CRYPTO_gcm128_finish
#define    CRYPTO_gcm128_init                HICRYPTO_CRYPTO_gcm128_init
#define    CRYPTO_gcm128_new                 HICRYPTO_CRYPTO_gcm128_new
#define    CRYPTO_gcm128_release             HICRYPTO_CRYPTO_gcm128_release
#define    CRYPTO_gcm128_setiv               HICRYPTO_CRYPTO_gcm128_setiv
#define    CRYPTO_gcm128_tag                 HICRYPTO_CRYPTO_gcm128_tag
#define    CRYPTO_nistcts128_decrypt         HICRYPTO_CRYPTO_nistcts128_decrypt
#define    CRYPTO_nistcts128_decrypt_block   HICRYPTO_CRYPTO_nistcts128_decrypt_block
#define    CRYPTO_nistcts128_encrypt         HICRYPTO_CRYPTO_nistcts128_encrypt
#define    CRYPTO_nistcts128_encrypt_block   HICRYPTO_CRYPTO_nistcts128_encrypt_block
#define    CRYPTO_ocb128_aad                 HICRYPTO_CRYPTO_ocb128_aad
#define    CRYPTO_ocb128_cleanup             HICRYPTO_CRYPTO_ocb128_cleanup
#define    CRYPTO_ocb128_copy_ctx            HICRYPTO_CRYPTO_ocb128_copy_ctx
#define    CRYPTO_ocb128_decrypt             HICRYPTO_CRYPTO_ocb128_decrypt
#define    CRYPTO_ocb128_encrypt             HICRYPTO_CRYPTO_ocb128_encrypt
#define    CRYPTO_ocb128_finish              HICRYPTO_CRYPTO_ocb128_finish
#define    CRYPTO_ocb128_init                HICRYPTO_CRYPTO_ocb128_init
#define    CRYPTO_ocb128_new                 HICRYPTO_CRYPTO_ocb128_new
#define    CRYPTO_ocb128_setiv               HICRYPTO_CRYPTO_ocb128_setiv
#define    CRYPTO_ocb128_tag                 HICRYPTO_CRYPTO_ocb128_tag
#define    CRYPTO_ofb128_encrypt             HICRYPTO_CRYPTO_ofb128_encrypt
#define    CRYPTO_xts128_encrypt             HICRYPTO_CRYPTO_xts128_encrypt
#define    int_bn_mod_inverse                HICRYPTO_int_bn_mod_inverse

#ifdef  __cplusplus
}
#endif
